services:
  helloagents:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    image: helloagents:team1237.v1
    container_name: helloagents
    restart: unless-stopped
    volumes:
      - $PWD:/learning
